### ISSUE TITLE
Move this repo to https://github.com/jakartaee

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/validation#179]
In the steering committee we voted to moved all specification projects from eclipse-ee4j to jakartaee. As such this repo should move to in due time.

Moving is fairly automatic, and redirects will be automatically put in place from the current location here to the new location.

If someone can authorise the move (e.g. @gunnarmorling @MattGill98) I can take care of it if needed.

Extra info:

"We voted on it in 2019 and then in 2020 we added it explicitly to our 2021 plan and voted on that plan.  I think we just need to start executing.  I sent about 30 emails like the following in an attempt to add some shape to it and kick off the move in the spec projects. 

 - https://www.eclipse.org/lists/jakartaee-platform-dev/msg02940.html
 - https://www.eclipse.org/lists/messaging-dev/msg00028.html
 - https://www.eclipse.org/lists/jakartaee-tck-dev/msg01417.html
 - https://www.eclipse.org/lists/ejb-dev/msg00264.html
"

From: https://www.eclipse.org/lists/jakarta.ee-spec/msg02073.html

Also note that many projects have indeed moved: https://github.com/jakartaee/

**Comment by MattGill98** [comment]
Sounds great - make it so 🎉

**Comment by arjantijms** [comment]
Repo has been moved ;) Thanks!

**Comment by gunnarmorling** [comment]
Thanks! Note that @gsmet and @starksm64 are Red Hat's representatives looking after Bean Validation/Jakarta EE these days; I'm not involved with it any longer.

**Comment by arjantijms** [comment]
@gunnarmorling too bad you aren't involved anymore, but it is what it is I guess. The project still lists you as the team lead: https://projects.eclipse.org/projects/ee4j.bean-validation/who

Maybe that needs to be updated?

**Comment by gunnarmorling** [comment]
Yes, that would be good indeed. We had some discussions internally before, I'll ping Guillaume and Scott again.
